dpi=(input("ingrese su dpi: "))
if len(dpi)==13 :
    print("dpi correcto")
    print("el candidato para presidente es partido rojo ")
    print("el candidato para presidente es partido azul ")
    presidente=input("ingrese su voto: ")
    print(presidente)
    print("el candidato para alcalde es partido rojo")
    print("el candidato para alcalde es partido azul")
    print("el candidato para alcalde es partido verde")
    print("el candidato para alcalde es partido morado")
    alcalde=input("ingrese su voto: ")
    print ("alcalde")
    print("se logro, nunca va a ganar la une")
else:
    print("dpi incorrecto")
    print("hello moto moto its incorrect")